apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
spec:
  type: {{ .Values.controller.service.type }}
  selector:
    app: nginx-ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80