apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: prod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: efs-logs
              mountPath: /usr/local/apache2/logs
      volumes:
        - name: efs-logs
          persistentVolumeClaim:
            claimName: apache-efs-pvc
