apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      chart: nginx-ingress
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.0.0
      values: |
        controller:
          replicaCount: 2
          ingressClass: nginx
          service:
            enabled: true
            type: LoadBalancer
            externalTrafficPolicy: Local
          metrics:
            enabled: true
    path: apps/ingress-controller  # Path to the chart in your repo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
