apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.0 # Specify the desired Helm chart version
    helm:
      values: |
        controller:
          replicaCount: 2
          ingressClass: nginx
          service:
            enabled: true
            type: LoadBalancer
            externalTrafficPolicy: Local
          metrics:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
