apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
