apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Keep existing scrape interval

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "node-exporter"
        static_configs:
          - targets: ["10.0.1.125:9100"]

      - job_name: "node-exporter"  # Keep service-based discovery
        static_configs:
          - targets: ["node-exporter-service.monitoring.svc.cluster.local:9100"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: "(.*):.*"
            replacement: "$1"

      - job_name: "cadvisor"  # NEW: Collects container metrics
        static_configs:
          - targets: ["cadvisor.monitoring.svc.cluster.local:8080"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: "(.*):.*"
            replacement: "$1"

      - job_name: "kube-state-metrics"  # NEW: Collects Kubernetes object status
        static_configs:
          - targets: ["kube-state-metrics.monitoring.svc.cluster.local:8080"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            regex: "(.*):.*"
            replacement: "$1"

      - job_name: "kubernetes-pods"  # NEW: Scrape individual pod metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
