apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: a5be16d5239874f39a5bbc7943cae151-0739733cdfa61156.elb.ap-south-1.amazonaws.com
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
